1. Importar as bibliotecas Pandas (pd) e math

In [1]:
import pandas as pd
import numpy as np
import math

2. Definir a variável "arquivo" pelo nome da planilha.

In [2]:
arquivo='dados_projeto1.xlsx'

3. Ler a planilha no Python. Escolha um nome para armazenar. Escolheremos df

In [3]:
df=pd.read_excel(arquivo)
df

   Escolaridade  Sexo  Idade
0      superior   fem     21
1      superior  masc     28
2   fundamental  masc     13
3         médio  masc     19
4         médio   fem     19
5      superior   fem     27
6   fundamental  masc     16
7         médio   fem     23
8   fundamental   fem     15
9      superior  masc     23
10        médio  masc     23
11     superior   fem     22
12  fundamental   fem     20
13        médio  masc     19
14     superior  masc     22
15        médio   fem     18

4.Agrupando os valores quantitativos a partir da variável selecionada.Escolhemos Idade (nome da coluna no arquivo df)

In [4]:
df1=df.Idade.value_counts()
df1

Idade
19    3
23    3
22    2
13    1
28    1
21    1
27    1
16    1
15    1
20    1
18    1
Name: count, dtype: int64

5. Ordenando os valores da variável

In [5]:
df1=df.Idade.value_counts().sort_index()
df1

Idade
13    1
15    1
16    1
18    1
19    3
20    1
21    1
22    2
23    3
27    1
28    1
Name: count, dtype: int64

6. Contando o total de elementos

In [6]:
totaldf1=df1.sum()
totaldf1

np.int64(16)

7. Montando a tabela de frequências da variável quantitativa discreta

7.1. Criar um DataFrame para a coluna desejada (dadosvquanti no exemplo)

In [7]:
dadosvquanti = pd.DataFrame(df1).reset_index()
dadosvquanti.columns = ['Idade', 'Frequência']

In [8]:
dadosvquanti

    Idade  Frequência
0      13           1
1      15           1
2      16           1
3      18           1
4      19           3
5      20           1
6      21           1
7      22           2
8      23           3
9      27           1
10     28           1

7.2 Calcular a frequência relativa em % com 2 casas decimais

In [9]:
dadosvquanti['Frequência Relativa (%)'] = round(dadosvquanti['Frequência'] * 100 / totaldf1, 2)

7.3 Criando uma nova tabela, renomeando as colunas

In [10]:
tabela=pd.DataFrame({"Idade":dadosvquanti['Idade'],"Frequência":dadosvquanti['Frequência'],"Frequência Relativa (%)":dadosvquanti['Frequência Relativa (%)']})

In [11]:
tabela

    Idade  Frequência  Frequência Relativa (%)
0      13           1                     6.25
1      15           1                     6.25
2      16           1                     6.25
3      18           1                     6.25
4      19           3                    18.75
5      20           1                     6.25
6      21           1                     6.25
7      22           2                    12.50
8      23           3                    18.75
9      27           1                     6.25
10     28           1                     6.25

**Montando as colunas das frequências acumuladas**

7.4 Frequências acumuladas

In [12]:
dadosvquanti['Frequência Acumulada']=np.cumsum(dadosvquanti['Frequência'])
dadosvquanti

    Idade  Frequência  Frequência Relativa (%)  Frequência Acumulada
0      13           1                     6.25                     1
1      15           1                     6.25                     2
2      16           1                     6.25                     3
3      18           1                     6.25                     4
4      19           3                    18.75                     7
5      20           1                     6.25                     8
6      21           1                     6.25                     9
7      22           2                    12.50                    11
8      23           3                    18.75                    14
9      27           1                     6.25                    15
10     28           1                     6.25                    16

In [13]:
dadosvquanti['Frequência Relativa Acumulada (%)']=np.cumsum(dadosvquanti['Frequência Relativa (%)'])
dadosvquanti

,Idade,Frequência,Frequência Relativa (%),Frequência Acumulada,Frequência Relativa Acumulada (%)
0,13,1,6.25,1,6.25
1,15,1,6.25,2,12.50
2,16,1,6.25,3,18.75
3,18,1,6.25,4,25.00
4,19,3,18.75,7,43.75
5,20,1,6.25,8,50.00
6,21,1,6.25,9,56.25
7,22,2,12.50,11,68.75
8,23,3,18.75,14,87.50
9,27,1,6.25,15,93.75
10,28,1,6.25,16,100.00

Ajustando a Tabela com colunas das frequências acumuladas

In [14]:
tabela=pd.DataFrame({"Idade":dadosvquanti['Idade'],"Frequência":dadosvquanti['Frequência'],"Frequência Relativa (%)":dadosvquanti['Frequência Relativa (%)'], "Frequência Acumulada":dadosvquanti['Frequência Acumulada'],"Frequência Relativa Acumulada (%)":dadosvquanti['Frequência Relativa Acumulada (%)']})

In [15]:
tabela

,Idade,Frequência,Frequência Relativa (%),Frequência Acumulada,Frequência Relativa Acumulada (%)
0,13,1,6.25,1,6.25
1,15,1,6.25,2,12.50
2,16,1,6.25,3,18.75
3,18,1,6.25,4,25.00
4,19,3,18.75,7,43.75
5,20,1,6.25,8,50.00
6,21,1,6.25,9,56.25
7,22,2,12.50,11,68.75
8,23,3,18.75,14,87.50
9,27,1,6.25,15,93.75
10,28,1,6.25,16,100.00

Caso queira enviar essa tabela para o Excel faça

tabela.to_excel("nome do arquivo.xlsx",sheet_name="nome da planilha",index=False)

In [16]:
# criaremos um arquivo de nome Tabela e uma planilha com nome Freq Idade
tabela.to_excel("Tabela.xlsx",sheet_name="Freq Idade",index=False)