1. Importar as bibliotecas "Pandas" e "Numpy" (Usaremos as abreviações pd e np, respectivamente, para faciliar a notação.
Importe também a biblioteca Math.

In [1]:
import pandas as pd
import numpy as np
import math

2. Defina a variável "arquivo" pelo nome do arquivo da planilha.
Defina também a variável "coluna". Essa variável definirá qual a variável será considerada para a construção da tabela.

In [2]:
arquivo = 'exemplo tabela.xlsx'
coluna = 'Sodium (mg)'

3. Leia a planilha no Phyton (para isso use o comando pd.read_excel(...) ). Dê um nome (nesse caso chamaremos de "df").

In [3]:
df=pd.read_excel(arquivo)
df

,Menu Category,Menu Items,Per Serve Size,Energy (kCal),Protein (g),Total fat (g),Sat Fat (g),Trans fat (g),Cholesterols (mg),Total carbohydrate (g),Total Sugars (g),Added Sugars (g),Sodium (mg)
0,Regular Menu,McVeggie™ Burger,168 g,40205,1024,1383,534,16,249,5654,79,449,70613
1,Regular Menu,McAloo Tikki Burger®,146 g,33952,85,1131,427,2,147,5027,705,407,54534
2,Regular Menu,McSpicy™ Paneer Burger,199 g,65276,2029,3945,1712,18,2185,5233,835,527,107458
3,Regular Menu,Spicy Paneer Wrap,250 g,67468,2096,391,1973,26,4093,5927,35,108,108746
4,Regular Menu,American Veg Burger,177 g,51217,153,2345,1051,17,2524,5696,785,476,105124
...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,Condiments Menu,Tomato Ketchup Sachets,8 g,1123,8,2345,0,1,8,263,233,164,7105
136,Condiments Menu,Maple Syrup,30 g,864,0,0,0,0,3,216,162,534,150
137,Condiments Menu,Cheese Slice,14 g,5103,306,399,289,1,1343,72,54,0,17895
138,Condiments Menu,Sweet Corn,40 g,4508,147,10,22,4,20,755,254,0,4
139,Condiments Menu,Mixed Fruit Beverage,180 ml,7225,65,2,2,2,1,180,1683,0,108

4. Montando Tabela de classes, indicando os limites de cada classe (note que a amplitude da classe é a mesma para todas as classes)
Neste caso precisamos antes saber o valor mínimo e o valor máximo dos dados para que todos estejam em pelo menos uma das classes.

In [4]:
valormin=df[coluna].min()
valormax=df[coluna].max()
print (valormin,valormax)

0 239949

Escolhendo os limites e montando a coluna de frequência absoluta.
NOTE QUE PARA A ESCOLHA DOS LIMITES E DA QUANTIDADE DE CLASSES DEVEMOS SEMPRE TER EM MENTE QUE A TABELA É UM RECURSO VISUAL PARA ORGANIZAÇÃO DE DADOS E NESSE CASO NÁO FAZ SENTIDO TER MUITAS LINHAS (PENSEM EM UMA QUANTIDADE DE NO MÁXIMO 10-12 LINHAS).

In [5]:
classes = [0,30000,60000,90000,120000, 150000,180000,210000,240000]
frequencia = pd.value_counts(pd.cut(x=df[coluna],bins=classes,include_lowest=True,right=False))
frequencia.sort_index(ascending=True)

/tmp/ipython-input-4249758906.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  frequencia = pd.value_counts(pd.cut(x=df[coluna],bins=classes,include_lowest=True,right=False))

Sodium (mg)
[0, 30000)          95
[30000, 60000)      16
[60000, 90000)      12
[90000, 120000)      9
[120000, 150000)     2
[150000, 180000)     3
[180000, 210000)     2
[210000, 240000)     1
Name: count, dtype: int64

5. Montando Frequência Relativa

In [6]:
Freqpercentual = round(pd.value_counts(pd.cut(x=df[coluna],bins=classes,include_lowest=True,right=False),normalize=True)*100,2)
Freqpercentual.sort_index(ascending=True)

/tmp/ipython-input-2202019940.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  Freqpercentual = round(pd.value_counts(pd.cut(x=df[coluna],bins=classes,include_lowest=True,right=False),normalize=True)*100,2)

Sodium (mg)
[0, 30000)          67.86
[30000, 60000)      11.43
[60000, 90000)       8.57
[90000, 120000)      6.43
[120000, 150000)     1.43
[150000, 180000)     2.14
[180000, 210000)     1.43
[210000, 240000)     0.71
Name: proportion, dtype: float64

6. Montando as colunas da frequência acumulada e da frequência relativa acumulada

In [7]:
#note que é necessário acumular a coluna da frequência com as classes ordenadas, isto é, usando sort_index
freqacum=np.cumsum(frequencia.sort_index())
freqacum

Sodium (mg)
[0, 30000)           95
[30000, 60000)      111
[60000, 90000)      123
[90000, 120000)     132
[120000, 150000)    134
[150000, 180000)    137
[180000, 210000)    139
[210000, 240000)    140
Name: count, dtype: int64

In [8]:
freqpercacum=np.cumsum(Freqpercentual.sort_index())
freqpercacum

Sodium (mg)
[0, 30000)           67.86
[30000, 60000)       79.29
[60000, 90000)       87.86
[90000, 120000)      94.29
[120000, 150000)     95.72
[150000, 180000)     97.86
[180000, 210000)     99.29
[210000, 240000)    100.00
Name: proportion, dtype: float64

7. Arrumando a Tabela

In [9]:
dist_freq = pd.DataFrame({'Frequência': frequencia,'Frequência Relativa (%)':Freqpercentual,'Freq.Acum.': freqacum,'Freq.Rel.Acum. (%)':freqpercacum})
print(dist_freq)
print(f'\n      Variável:{coluna}')
print('     *Limites superiores do intervalo de classes não incluídos')

                  Frequência  Frequência Relativa (%)  Freq.Acum.  \
Sodium (mg)
[0, 30000)                95                    67.86          95
[30000, 60000)            16                    11.43         111
[60000, 90000)            12                     8.57         123
[90000, 120000)            9                     6.43         132
[120000, 150000)           2                     1.43         134
[150000, 180000)           3                     2.14         137
[180000, 210000)           2                     1.43         139
[210000, 240000)           1                     0.71         140

                  Freq.Rel.Acum. (%)
Sodium (mg)
[0, 30000)                     67.86
[30000, 60000)                 79.29
[60000, 90000)                 87.86
[90000, 120000)                94.29
[120000, 150000)               95.72
[150000, 180000)               97.86
[180000, 210000)               99.29
[210000, 240000)              100.00

      Variável:Sodium (mg)
     *Limites superiores do intervalo de classes não incluídos